[2018-11-08 21:27:00] [    INFO] --- Setup logging. Log file: ./output/gt1/MNIST/output_channels=10/no_cuda=True/08-11-18-21h-27m-00s/logs.txt (setup.py:531)
[2018-11-08 21:27:00] [    INFO] --- Arguments saved to: ./output/gt1/MNIST/output_channels=10/no_cuda=True/08-11-18-21h-27m-00s/args.txt (setup.py:534)
[2018-11-08 21:27:00] [    INFO] --- Initialize Tensorboard SummaryWriter (setup.py:539)
[2018-11-08 21:27:02] [ WARNING] --- Git status is ignored! (RunMe.py:205)
[2018-11-08 21:27:02] [    INFO] --- Randomly chosen seed is: 2229463349 (setup.py:616)
[2018-11-08 21:27:02] [    INFO] --- Model CNN_basic expects input size of (32, 32) (my_task.py:89)
[2018-11-08 21:27:02] [    INFO] --- Loading MNIST from:../SETS/MNIST (setup.py:61)
[2018-11-08 21:27:03] [    INFO] --- Setting up model CNN_basic (setup.py:86)
[2018-11-08 21:27:03] [    INFO] --- Loading weights for data balancing (setup.py:101)
[2018-11-08 21:27:03] [    INFO] --- Loading a saved model (setup.py:117)
[2018-11-08 21:27:03] [   ERROR] --- Unhandled error: TypeError("'NoneType' object is not subscriptable",) (RunMe.py:261)
[2018-11-08 21:27:03] [   ERROR] --- Traceback (most recent call last):
  File "./template/RunMe.py", line 254, in _execute
    **args.__dict__)
  File "/home/dusan/DeepDIVA/template/runner/my_task/my_task.py", line 112, in single_run
    raw_image = cv2.imread('test_sl.png')[..., ::-1]
TypeError: 'NoneType' object is not subscriptable
 (RunMe.py:262)
[2018-11-08 21:27:03] [   ERROR] --- Execution finished with errors :( (RunMe.py:263)
