[2018-11-01 22:18:45] [    INFO] --- Setup logging. Log file: log/Test_1/MNIST/lr=0.1/no_cuda=True/01-11-18-22h-18m-45s/logs.txt (setup.py:531)
[2018-11-01 22:18:45] [    INFO] --- Arguments saved to: log/Test_1/MNIST/lr=0.1/no_cuda=True/01-11-18-22h-18m-45s/args.txt (setup.py:534)
[2018-11-01 22:18:45] [    INFO] --- Initialize Tensorboard SummaryWriter (setup.py:539)
[2018-11-01 22:18:48] [ WARNING] --- Git status is ignored! (RunMe.py:205)
[2018-11-01 22:18:48] [    INFO] --- Randomly chosen seed is: 4179424768 (setup.py:616)
[2018-11-01 22:18:48] [    INFO] --- Model CNN_basic expects input size of (32, 32) (image_classification.py:63)
[2018-11-01 22:18:48] [    INFO] --- Loading MNIST from:new_datasets/MNIST (setup.py:234)
[2018-11-01 22:18:48] [ WARNING] --- Missing analytics.csv file for dataset located at new_datasets/MNIST (setup.py:385)
[2018-11-01 22:18:48] [ WARNING] --- Attempt creating analytics.csv file for dataset located at new_datasets/MNIST (setup.py:387)
[2018-11-01 22:18:48] [    INFO] --- Begin computing the mean (dataset_analytics.py:133)
[2018-11-01 22:18:51] [    INFO] --- Finished computing the mean (dataset_analytics.py:142)
[2018-11-01 22:18:51] [    INFO] --- Begin computing the std (dataset_analytics.py:143)
[2018-11-01 22:18:54] [    INFO] --- Finished computing the std (dataset_analytics.py:150)
[2018-11-01 22:18:54] [    INFO] --- Begin computing class frequencies weights (dataset_analytics.py:202)
[2018-11-01 22:18:54] [    INFO] --- Finished computing class frequencies weights (dataset_analytics.py:219)
[2018-11-01 22:18:54] [    INFO] --- Class frequencies (rounded): [ 9.87 11.24  9.93 10.22  9.74  9.04  9.86 10.44  9.75  9.91] (dataset_analytics.py:221)
[2018-11-01 22:18:54] [ WARNING] --- Created analytics.csv file for dataset located at new_datasets/MNIST  (setup.py:389)
[2018-11-01 22:18:54] [    INFO] --- Dataset loaded as images (setup.py:259)
[2018-11-01 22:18:54] [    INFO] --- Verifying the dataset integrity - quick (dataset_integrity.py:182)
[2018-11-01 22:18:54] [   ERROR] --- Missing footprint. Cannot verify dataset integrity. (dataset_integrity.py:197)
[2018-11-01 22:18:54] [ WARNING] --- Creating a new footprint, since it is missing. (dataset_integrity.py:198)
[2018-11-01 22:18:54] [    INFO] --- Generating the footprint of: new_datasets/MNIST (dataset_integrity.py:54)
[2018-11-01 22:18:58] [    INFO] --- Footprint generated successfully (dataset_integrity.py:57)
[2018-11-01 22:18:59] [    INFO] --- Setting up model CNN_basic (setup.py:86)
[2018-11-01 22:19:00] [    INFO] --- Loading weights for data balancing (setup.py:101)
[2018-11-01 22:19:00] [    INFO] --- Begin training (image_classification.py:76)
[2018-11-01 22:19:03] [    INFO] --- val   epoch[-1]: Acc@1=13.025	Loss=2.2987	Batch time=0.016 (0.002 to load data) (evaluate.py:151)
[2018-11-01 22:19:32] [    INFO] --- val   epoch[0]: Acc@1=97.242	Loss=0.0932	Batch time=0.016 (0.003 to load data) (evaluate.py:151)
[2018-11-01 22:20:00] [    INFO] --- val   epoch[1]: Acc@1=98.042	Loss=0.0634	Batch time=0.016 (0.002 to load data) (evaluate.py:151)
[2018-11-01 22:20:29] [    INFO] --- val   epoch[2]: Acc@1=98.417	Loss=0.0516	Batch time=0.016 (0.002 to load data) (evaluate.py:151)
[2018-11-01 22:20:57] [    INFO] --- val   epoch[3]: Acc@1=98.475	Loss=0.0483	Batch time=0.016 (0.002 to load data) (evaluate.py:151)
[2018-11-01 22:21:26] [    INFO] --- val   epoch[4]: Acc@1=98.350	Loss=0.0500	Batch time=0.016 (0.002 to load data) (evaluate.py:151)
[2018-11-01 22:21:26] [    INFO] --- Loading the best model before evaluating on the test set. (image_classification.py:99)
[2018-11-01 22:21:26] [    INFO] --- Setting up model CNN_basic (setup.py:86)
[2018-11-01 22:21:26] [    INFO] --- Loading weights for data balancing (setup.py:101)
[2018-11-01 22:21:26] [    INFO] --- Loading a saved model (setup.py:117)
[2018-11-01 22:21:29] [    INFO] --- test  epoch[4]: Acc@1=98.210	Loss=0.0524	Batch time=0.016 (0.002 to load data) (evaluate.py:151)
[2018-11-01 22:21:29] [    INFO] --- Training completed (image_classification.py:111)
[2018-11-01 22:21:29] [    INFO] --- Time taken for train/eval/test is: 0:02:41 (RunMe.py:257)
